//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerFinder2.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindowLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set
            {
                this["MainWindowLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("982, 631")]
        public global::System.Drawing.Size MainWindowSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["MainWindowSize"]));
            }
            set
            {
                this["MainWindowSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainWindowState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainWindowState"]));
            }
            set
            {
                this["MainWindowState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DebugLogLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["DebugLogLocation"]));
            }
            set
            {
                this["DebugLogLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083, 593")]
        public global::System.Drawing.Size DebugLogSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["DebugLogSize"]));
            }
            set
            {
                this["DebugLogSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CodeNoteConverterLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["CodeNoteConverterLocation"]));
            }
            set
            {
                this["CodeNoteConverterLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("612, 439")]
        public global::System.Drawing.Size CodeNoteConverterSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["CodeNoteConverterSize"]));
            }
            set
            {
                this["CodeNoteConverterSize"] = value;
            }
        }

        // Added settings properties to store the window's position and size.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CodeNoteHierarchyFixerLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["CodeNoteHierarchyFixerLocation"]));
            }
            set
            {
                this["CodeNoteHierarchyFixerLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size CodeNoteHierarchyFixerSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["CodeNoteHierarchyFixerSize"]));
            }
            set
            {
                this["CodeNoteHierarchyFixerSize"] = value;
            }
        }
    }
}